from __future__ import annotations

import json
from pathlib import Path

import streamlit as st


REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = REPO_ROOT / "reports" / "executive_dashboard.json"
WARNING = (
    "This is a prototype dashboard and report index only. It is not legal advice, tax advice, ATO guidance, "
    "Treasury modelling, economic validation, welfare advice, compliance scoring, enforcement, not operational readiness, "
    "not legal sufficiency, not legislative readiness, not a readiness score, and not an official review pathway."
)


def load_report(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def rows_for_layers(layers: list[dict]) -> list[dict]:
    return [
        {
            "Read Order": item.get("read_order"),
            "Layer ID": item.get("layer_id"),
            "Layer Name": item.get("layer_name"),
            "Group": item.get("layer_group"),
            "Status Labels": ", ".join(item.get("status_labels", [])),
            "Primary Reports": ", ".join(item.get("primary_reports", [])),
            "Reviewers": ", ".join(item.get("recommended_reviewer", [])),
        }
        for item in layers
    ]


def rows_for_reports(entries: list[dict]) -> list[dict]:
    return [
        {
            "Report": item.get("report_path"),
            "Layer ID": item.get("layer_id"),
            "Exists": item.get("exists"),
            "Generated By": item.get("generated_by"),
            "Warning": item.get("interpretation_warning"),
            "Read Order": item.get("recommended_read_order"),
        }
        for item in entries
    ]


def rows_for_blockers(blockers: list[dict]) -> list[dict]:
    return [
        {
            "Layer ID": item.get("layer_id"),
            "Type": item.get("blocker_type"),
            "Blocker": item.get("blocker"),
            "External Review": item.get("external_review_needed"),
            "Main Reason": item.get("main_reason"),
        }
        for item in blockers
    ]


def rows_for_profiles(profiles: list[dict]) -> list[dict]:
    return [
        {
            "Layer ID": item.get("layer_id"),
            "Non-Claim Flags": ", ".join(item.get("non_claim_flags", [])),
            "Must Not Be Used For": ", ".join(item.get("must_not_be_used_for", [])),
            "Not For Real-World Use": item.get("not_for_real_world_use"),
        }
        for item in profiles
    ]


st.set_page_config(page_title="CARSF Executive Dashboard", layout="wide")
st.title("Executive Dashboard")
st.caption("Consolidated prototype report index and review navigation.")
st.warning(WARNING)
st.error("No readiness score, maturity score, approval, operational-readiness claim, legal-sufficiency claim, validation claim, or liability change is created.")

report = load_report(REPORT_PATH)
if not report:
    st.info("Run `python scripts/run_executive_dashboard.py` to generate executive dashboard reports.")
    st.stop()
    raise SystemExit(0)

metadata = report.get("metadata", {})
dashboard = report.get("executive_dashboard", {})
summary = report.get("summary", {})

st.markdown("### Prototype Stack Summary")
st.table(
    [
        {"Metric": key, "Value": str(value)}
        for key, value in summary.items()
        if isinstance(value, (int, bool, str))
    ]
)

st.markdown("### Required False Flags")
st.table(
    [
        {"Flag": key, "Value": str(metadata.get(key))}
        for key in [
            "real_data_used",
            "readiness_score_created",
            "operational_readiness_claimed",
            "legal_sufficiency_claimed",
            "economic_validation_claimed",
            "firm_level_liability_logic_modified",
        ]
    ]
)

st.markdown("### Suggested Review Navigation")
st.table(
    [
        {
            "Read Order": item.get("read_order"),
            "Layer ID": item.get("layer_id"),
            "Layer Name": item.get("layer_name"),
            "Official Process": item.get("official_process"),
            "Main Reason": item.get("main_reason"),
        }
        for item in dashboard.get("suggested_review_navigation", [])
    ]
)

st.markdown("### Layer Index")
st.table(rows_for_layers(dashboard.get("layers", [])))

st.markdown("### Report Index")
st.table(rows_for_reports(dashboard.get("report_entries", [])))

st.markdown("### Streamlit Page Index")
st.table([{"Page": page} for page in dashboard.get("streamlit_page_index", [])])

st.markdown("### Calibration Blockers")
st.table(rows_for_blockers(dashboard.get("calibration_blockers", [])))

st.markdown("### External Review Blockers")
st.table(rows_for_blockers(dashboard.get("external_review_blockers", [])))

st.markdown("### Non-Claim Profile by Layer")
st.table(rows_for_profiles(dashboard.get("non_claim_profiles", [])))

st.markdown("### Guardrail / Safety Status")
st.table(
    [
        {
            "Source Report": item.get("source_report"),
            "Exists": item.get("exists"),
            "Clean": item.get("clean"),
            "Denied Findings": item.get("denied_findings"),
            "Warning Findings": item.get("warning_findings"),
            "Warning": item.get("interpretation_warning"),
        }
        for item in dashboard.get("guardrail_statuses", [])
    ]
)

st.markdown("### Missing Reports or Navigation Gaps")
gaps = dashboard.get("missing_reports_or_navigation_gaps", [])
if gaps:
    for gap in gaps:
        st.markdown(f"- {gap}")
else:
    st.markdown("- No required dashboard report paths are missing.")

st.markdown("### Non-Claims")
for item in metadata.get("non_claims", [WARNING]):
    st.markdown(f"- {item}")
