from __future__ import annotations

import json
import subprocess
import sys

from carsf.executive_dashboard import (
    EXECUTIVE_DASHBOARD_WARNING,
    find_forbidden_affirmative_dashboard_claims,
)


def test_executive_dashboard_report_generates_json_and_markdown(repo_root) -> None:
    reports_dir = repo_root / "tmp" / "test-executive-dashboard"
    completed = subprocess.run(
        [sys.executable, "scripts/run_executive_dashboard.py", "--reports-dir", str(reports_dir)],
        cwd=repo_root,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr
    assert (reports_dir / "executive_dashboard.md").exists()
    assert (reports_dir / "executive_dashboard.json").exists()


def test_executive_dashboard_report_includes_non_claim_language_and_false_flags(repo_root) -> None:
    reports_dir = repo_root / "tmp" / "test-executive-dashboard-nonclaims"
    subprocess.run(
        [sys.executable, "scripts/run_executive_dashboard.py", "--reports-dir", str(reports_dir)],
        cwd=repo_root,
        check=True,
    )
    markdown = (reports_dir / "executive_dashboard.md").read_text(encoding="utf-8")
    payload = json.loads((reports_dir / "executive_dashboard.json").read_text(encoding="utf-8"))

    assert EXECUTIVE_DASHBOARD_WARNING in markdown
    assert EXECUTIVE_DASHBOARD_WARNING in payload["metadata"]["non_claims"]
    for key in [
        "real_data_used",
        "readiness_score_created",
        "operational_readiness_claimed",
        "legal_sufficiency_claimed",
        "economic_validation_claimed",
        "firm_level_liability_logic_modified",
    ]:
        assert payload["metadata"][key] is False
        assert payload["summary"][key] is False


def test_executive_dashboard_report_contains_required_sections(repo_root) -> None:
    reports_dir = repo_root / "tmp" / "test-executive-dashboard-sections"
    subprocess.run(
        [sys.executable, "scripts/run_executive_dashboard.py", "--reports-dir", str(reports_dir)],
        cwd=repo_root,
        check=True,
    )
    markdown = (reports_dir / "executive_dashboard.md").read_text(encoding="utf-8")

    for heading in [
        "## F. Layer Index",
        "## G. Report Index",
        "## H. Streamlit Page Index",
        "## I. Non-Claim Profile by Layer",
        "## J. Calibration Blockers",
        "## K. External Review Blockers",
        "## Q. Recommended Reviewer Routing",
    ]:
        assert heading in markdown


def test_executive_dashboard_report_contains_required_tables(repo_root) -> None:
    reports_dir = repo_root / "tmp" / "test-executive-dashboard-tables"
    subprocess.run(
        [sys.executable, "scripts/run_executive_dashboard.py", "--reports-dir", str(reports_dir)],
        cwd=repo_root,
        check=True,
    )
    markdown = (reports_dir / "executive_dashboard.md").read_text(encoding="utf-8")

    assert "Layer ID | Layer Name | Group | Purpose | Status Labels" in markdown
    assert "Report | Layer ID | Exists | Generated By | Interpretation Warning" in markdown
    assert "Layer ID | Blocker Type | Blocker | External Review Needed" in markdown
    assert "Reviewer | Layers" in markdown


def test_executive_dashboard_report_has_no_forbidden_affirmative_readiness_or_validation_claims(repo_root) -> None:
    reports_dir = repo_root / "tmp" / "test-executive-dashboard-forbidden"
    subprocess.run(
        [sys.executable, "scripts/run_executive_dashboard.py", "--reports-dir", str(reports_dir)],
        cwd=repo_root,
        check=True,
    )
    combined = "\n".join(path.read_text(encoding="utf-8") for path in reports_dir.glob("executive_dashboard.*"))

    assert find_forbidden_affirmative_dashboard_claims(combined) == []


def test_streamlit_executive_dashboard_page_and_main_app_import_without_error(repo_root) -> None:
    for script in ["simulator/app.py", "simulator/pages/25_Executive_Dashboard.py"]:
        completed = subprocess.run(
            [sys.executable, "-c", f"import runpy; runpy.run_path({script!r}, run_name='__main__')"],
            cwd=repo_root,
            check=False,
            capture_output=True,
            text=True,
        )

        assert completed.returncode == 0, completed.stderr


def test_ci_runs_executive_dashboard_runner_before_evidence_and_guardrails(repo_root) -> None:
    workflow = (repo_root / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")

    legislative_index = workflow.index("python scripts/run_legislative_architecture.py")
    dashboard_index = workflow.index("python scripts/run_executive_dashboard.py")
    evidence_index = workflow.index("python scripts/run_evidence_workflow.py")
    guardrail_index = workflow.index("python scripts/run_repo_guardrails.py")

    assert legislative_index < dashboard_index < evidence_index < guardrail_index
